### ISSUE TITLE
Next.js 7 / Webpack 4 compatibility

### ISSUE THREAD

**Issue by martpie** [martpie/next-plugin-transpile-modules#1]
This plugin oddly does not work with Next 7. I spent multiple hours trying to figure out what was going wrong without success.

Refs:

- Next 7 release: https://github.com/zeit/next.js/releases/tag/7.0.0
- Did rules include/exclude behavior change in Webpack 4? webpack/webpack#8077

I still do not know if the problem comes from Webpack or Next's custom Babel loaders.

Any hints/help would be highly appreciated.

---

### Temporary solutions:

- https://github.com/martpie/next-plugin-transpile-modules/issues/1#issuecomment-427749256
- https://github.com/martpie/next-plugin-transpile-modules/issues/1#issuecomment-425839242

**Comment by martpie** [comment]
Oh is it? I got errors when using it with Next's `withTypescript`.

I should write tests for both scenarios, it should not be too hard.

**Comment by martpie** [comment]
![screen shot 2018-09-26 at 14 29 17](https://user-images.githubusercontent.com/1311607/46079845-9263bd80-c198-11e8-8d21-629e06acd021.png)

And I also saw this comment saying it was not working: https://github.com/zeit/next.js/pull/3732#issuecomment-423302026

**Comment by alexanbj** [comment]
I don't think this has something to do with TS. I  don't use TS and it doesn't work for me either with Next 7.

**Comment by martpie** [comment]
I don’t think the problem comes from Webpack but Babel... I will have to dive into Next’s build codebase.

If anyone has interesting inputs/advices... feel free! 😅

**Comment by azizhk** [comment]
Ok I realized I need to wrap the externals with a `options.isServer` check like

https://github.com/zeit/next.js/blob/3a059688a8a0e10342ce697c89a7faebbeca9629/build/webpack.js#L31-L33

Creating PR.

**Comment by azizhk** [comment]
```
node_modules/
  want_to_transpile/
    node_modules/
      dont_want_to_transpile/
  third_party/
  next/
```
So I think this might be the problem. My `dont_want_to_transpile` module which is a dependency of `want_to_transpile` module is being bundled by webpack. (Which it should not).

Now that `dont_want_to_transpile`is requiring `third_party` module which is not bundled (expected)
But it is expecting that `third_party` module be transpiled.

But at bundling time, it resolved to a non-transpiled (esm) source code. So it assumed that path and saved it while bundling `dont_want_to_transpile` module.

So I think webpack needs to give us fine grained control over which bundling `want_to_transpile` and marking `want_to_transpile/node_modules/*` as external.

**Comment by azizhk** [comment]
And as to why my build works when I comment externals code is because my `want_to_transpile` module also has es2015 code published in dist.

But for a module which does not publish es2015 code, commenting externals would not work. So my solution wont-fix.

**Comment by martpie** [comment]
I faced some problems with node_modules regexs too. If I want to transpile `shared`, `node_modules/any-other-module/shared` will be transpiled.

I can replace that with custom functions instead of Regex. It should make the code more readable too. But I still get the transpilation problem.

**Comment by morajabi** [comment]
I have the same issue, but for striping "flow" types in a monorepo:
```
- monorepo root
   - shared // <- trying to transpile this
   - web
   - - next.config.js

**Comment by morajabi** [comment]
Looks like it doesn't pick up the correct ".babelrc" because of a breaking change on how babel looks for config.

**Comment by martpie** [comment]
@morajabi So are you saying this is a problem in the user's setup or Next's setup?

**Comment by morajabi** [comment]
Not user setup most likely. I think we need to figure out a way to adopt to the new Babel behaviour.

**Comment by azizhk** [comment]
Create react app version 2 is transpiling npm packages. We can learn from
there.

**Comment by reicheltp** [comment]
It does not pick the `.babelrc`. As a temporary workaround you can add your babel presets / plugins like this:

```js
const withTranspileModules = require('next-plugin-transpile-modules')
module.exports = withTranspileModules({
  transpileModules: ['@my_namespace'],
  webpack: (config, { defaultLoaders }) => {
    defaultLoaders.babel.options.presets = ['@babel/flow']
    defaultLoaders.babel.options.plugins = [
      ['react-native-web', { commonjs: true }],
    ]

    return config
  },
})
```

**Comment by martpie** [comment]
Similar to https://github.com/zeit/next.js/issues/5288

**Comment by morajabi** [comment]
Thanks @reicheltp @martpie, the temporary workaround worked perfectly for me. (monorepo)

**Comment by martpie** [comment]
Ok, after countrless hours reading changelogs and poorly documented Babel 7 changes, I managed to transpile a local symlinked package from `node_modules`. The secret is to declare a babel.config.js with some rules in it.

I do not like it because it is just rewriting config files that should be done by Next already, but waiting for a cleaner solution, I'll update the package and the documentation soon.

**Comment by martpie** [comment]
For those interested, the quick fix: 

```
// babel.config.js (in your Next.js folder)
module.exports = (api) => {
  api.cache(true);

  const presets = [
    'next/babel',
    '@zeit/next-typescript/babel'
  ];

  return {
    presets
  };
}
```

I am checking if I can do this automatically via the plugin.

**Comment by Mtnt** [comment]
Any updates? I tried make a fix as shown at https://github.com/martpie/next-plugin-transpile-modules/issues/1#issuecomment-427749256, but still got an error:

I`m use `propTypes` from some child component to declare parent`s and got `Cannot read property '__propName__' of undefined`

**Comment by martpie** [comment]
@Mtnt Do you have a piece of code to share so I can reproduce this error?

**Comment by Mtnt** [comment]
@martpie 

**It`s an assignment of props for npm module "@sample-ns/controlls"**
```
const { type: controlType, ...controlProps } = Control.propTypes;
const { type: groupType, ...groupProps } = Group.propTypes;

Checkbox.propTypes = controlProps;
Radio.propTypes = controlProps;
RadioGroup.propTypes = groupProps;
CheckboxGroup.propTypes = groupProps;
```

**next.config.js**
```
module.exports = withPlugins([
  [
    withTM,
    {transpileModules: ['@sample-ns']},
  ],
]);
```
So, it`s transformed to
```
var _Control$propTypes = control.propTypes,
    controlType = _Control$propTypes.type,
    controlProps = _objectWithoutProperties(_Control$propTypes, ["type"]);

var _Group$propTypes = group.propTypes,
    groupType = _Group$propTypes.type,
    groupProps = _objectWithoutProperties(_Group$propTypes, ["type"]);
```

and fires an exception on `_Control$propTypes.type`

is it enough?

**Comment by martpie** [comment]
Have you checked if it was working well with Next.js 6?

**Comment by Mtnt** [comment]
yeah, it did

**Comment by Mtnt** [comment]
@martpie wow, suddenly - it did not oO. I missed a commit that added some changes. Sorry...

However, there is still a problem... that prop types did not cropped. I created the 'type' variable only for omitting it in `Checkbox.propType` and expected that all code will be removed.
Any advice for fast fix?

**Comment by curran** [comment]
FWIW here's an example that shows transpiling _working_ with Next 7, but not _watching_.

https://github.com/curran/nextjs-esm-example/pull/4

Struggling to get watching to work.

Tracked as #5

**Comment by tsirlucas** [comment]
Temporary solutions stoped working on most recent canary versions (even in 7.0.2 canary versions, but also in 8.0.0 most recent one)... For some reason if the transpiled dependency entry file imports some code from subfolders, we end up with a unstranspiled import on our app.

Instead of importing from `node_modules/dependency/components/ComponentA` we end up with `./components/ComponentA` and that leads to import errors.

Also, tried this library with the new `target: serverless` option and it seems not to work for some reason. Maybe this plugin shouldn't work on serverless environment? Maybe its not working due to the import error that im getting locally.

I'll try to create a repo reproducing both cases and post it here

**Comment by martpie** [comment]
I did not play with Next 8 yet but I subscribed to the releases. I am going to investigate over the week-end where things fail.

**Comment by tsirlucas** [comment]
Here is the repo with the `7.0.2-canary.31` version where we can already reproduce the import problems, so I guess the problem its between `7.0.2` and `7.0.2-canary.31`

https://github.com/tsirlucas/next-transpile-errors.

To reproduce the same thing in the `8.0.0` version you can just update it to `8.0.0-canary.13`.
Also, the commit adding serverless target its on `7.0.2-canary.50`, so I guess the problem is not really the serverless config.

**Comment by azizhk** [comment]
So I went through @tsirlucas project. I changed 
https://github.com/martpie/next-plugin-transpile-modules/blob/c85c175d9fdf122fddddbaa9d8fc14ec6d4407b0/index.js#L30-L34
to 
```js
const path = require('path')
config.externals = config.externals.map(external => {
  if (typeof external !== 'function') return external
  return (ctx, req, cb) => {
    return includes.find(include => 
      req.startsWith('.')
        ? include.test(path.resolve(ctx, req))
        : include.test(req)
    )
      ? cb()
      : external(ctx, req, cb);
  }
})
```
And got some things working. Though am just shooting in the dark here.

**Comment by martpie** [comment]
Let's move the discussion about Next 8 in #8 ;)

**Comment by martpie** [comment]
After talking to Next.js maintainers, it is actually not a bug, when you use plugins that use babel, like typescript or flow, you need to update your `.babelrc` accordingly as documented in the plugins. I will update the readme and close this issue.
