### ISSUE TITLE
Transpile not working on scoped packages

### ISSUE THREAD

**Issue by aluminick** [martpie/next-plugin-transpile-modules#10]
This works
```js
module.exports = withTM({
  transpileModules: ['@foo']
})
```
but this doesn't
```js
module.exports = withTM({
  transpileModules: ['@foo/bar']
})
```

**Comment by martpie** [comment]
I see the issue, but could you explain a bit more in details how your project is setup and how you install your dependencies?

**Comment by martpie** [comment]
Maybe I can explain more in details my concert: dependencies should not be monorepos (the philosophy is "1 package does 1 thing"). 

Eventually, each package of this monorepo should be **published separately** or **installed separately** in your Next.js package.json, but install a monorepo as a dependency definitely looks like a "setup smell" to me. ;)

**Comment by aluminick** [comment]
@martpie I did not install the monorepo as dependency the package that I installed is @foo/bar.
I don't think transpiling the whole thing doesn't make sense since only a few packages requires transpiling. I think it's gonna use more computer resource than it should, I assume it's stored in memory.

**Comment by martpie** [comment]
Ooooh sorry, I understand the problem, my bad!

I'll investigate!

**Comment by martpie** [comment]
I cannot manage to reproduce it, scoped package works well on my setup, both for hot-reload and transpilation.

Can you still reproduce it with the latest version of the plugin? Also can you give me the name of the plugin you try to transpile (if not private), your OS, your npm version and your node version?

**Comment by aluminick** [comment]
I'm currently using the latest version. I'm trying to transpile material-components-web, node v8.11.2, npm 6.4.1, OS ubuntu 16.04. Thank you for your quick reply.

**Comment by martpie** [comment]
Can you provide a repository with a reproduction of this bug? It's a little bit of work but it would significantly help.

**Comment by aluminick** [comment]
I'll create one. I'll just ping you later.

**Comment by aluminick** [comment]
@martpie I get it to work. I just have to include the both the packages. The package to be transpiled and the one using it. Thanks
