### ISSUE TITLE
"You may need an appropriate loader?" error using next7

### ISSUE THREAD

**Issue by KingScooty** [martpie/next-plugin-transpile-modules#7]
So i'm not doing anything special. Have a few shared (via lerna/yarn workspaces monorepo structure) react components using styled components.

My `babel.config.js` file looks like this:

```js
// babel.config.js (in your Next.js folder)
module.exports = api => {
	api.cache(true);

	const presets = ["next/babel"];

	const plugins = ["styled-components"];

	return {
		presets,
		plugins
	};
};
```

and my `next.config.js` file looks like:

```js
const withTM = require("next-plugin-transpile-modules");
const withCSS = require("@zeit/next-css");
const withImages = require("next-images");

// Tell webpack to compile the "bar" package
// https://www.npmjs.com/package/next-plugin-transpile-modules
module.exports = withImages(
	withCSS(
		withTM({
			transpileModules: ["dh-ui-atom", "dh-ui-post"]
		})
	)
);
```

Running `yarn dev` in my next project runs, but when i try and load the page, i get the following error:

```
Module parse failed: Unexpected token (20:2)
You may need an appropriate loader to handle this file type.
| 	 */
| 	return (
> 		<div className={logoClasses}>
```

Weirdly, if i comment out the entries inside `transpileModules`, everything compiles fine, and the site loads, but then obviously none of the changes are being watched/hot reloaded, so it seems to be a local issue to transpile modules. 

What am i doing wrong?

**Comment by martpie** [comment]
Yarn is not supported because it copies dependencies instead of symlinking them. This is why hot-reloading is not working.

I will add a comment about that in the README because it is a common mistake.

Yarn workspaces work fine though. 

I advice two things: 

- Read https://github.com/martpie/next-plugin-transpile-modules/issues/5 : Lerna is not a tool to manage monorepos dependencies
- Check the `with-yarn-workspaces` example on the official repo https://github.com/zeit/next.js/tree/canary/examples/with-yarn-workspaces

Tell me if it solves it for you :)

**Comment by martpie** [comment]
I just added a FAQ to the README fyi.

**Comment by KingScooty** [comment]
I am actually already using yarn workspaces though! Just lerna for versioning.

**Comment by martpie** [comment]
Have you tried this? https://github.com/martpie/next-plugin-transpile-modules/blob/master/README.md#i-have-trouble-making-it-work-with-nextjs-7

**Comment by KingScooty** [comment]
Yeah i've followed all the steps properly. I'm not sure what i've done wrong for a loader to be missing for JSX?

**Comment by martpie** [comment]
You may need to adapt the `babel.config.js` to your needs though.

Can you provide an example/repo so I can reproduce your problem?

**Comment by KingScooty** [comment]
It seemed to be an issue with one of the canary releases of next. I'm having to use canary releases due to the webpack upgrade that's included in them.

I can confirm this issue has gone away, but the hot reloading issue has come back. (`next: ^7.0.2-canary.41`)

**Comment by martpie** [comment]
I’ll try to test this plugin with Canary to prevent a future incompatibility

**Comment by cyberwombat** [comment]
@martpie Can you elucidate:
"Yarn is not supported", "Yarn workspaces work fine though."

How would I use yarn workspaces without using yarn? I'm using yarn workspaces and cannot get next to transpile typescript using this module.

**Comment by martpie** [comment]
This issue is 2 years old, please open a new one

**Comment by martpie** [comment]
By "yarn is not supported", I meant `yarn add ../../something` is not supported ;)
